server:
  port: 8060
spring:
  application:
    name: API-GATEWAY02
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     # Routes dynamiques depuis Eureka
          lower-case-service-id: true
      routes:
        - id: product-composite
          uri: lb://PRODUCT-COMPOSITE-SERVICE
          predicates:
            - Path=/product-composite/**
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
